name: .NET

on: [pull_request]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo "WELCOME"
  build:
    runs-on: ubuntu-latest
    needs: welcome
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: build
        run: dotnet build Actions-Kata.sln
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: test
        run: dotnet test
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: publish
        run: dotnet publish
